In [8]:
from bs4 import BeautifulSoup as bs
import requests
import lxml.html as lx_html
import pandas as pd
import numpy as np


url = "https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M"
res = requests.get(url)
soup = bs(res.content,'lxml')
table = soup.find_all('table')[0]
df = pd.read_html(str(table))
data = pd.read_json(df[0].to_json(orient='records'))

In [17]:
data

,Postal Code,Borough,Neighbourhood
0,M1A,Not assigned,Not assigned
1,M2A,Not assigned,Not assigned
2,M3A,North York,Parkwoods
3,M4A,North York,Victoria Village
4,M5A,Downtown Toronto,"Regent Park, Harbourfront"
...,...,...,...
175,M5Z,Not assigned,Not assigned
176,M6Z,Not assigned,Not assigned
177,M7Z,Not assigned,Not assigned
178,M8Z,Etobicoke,"Mimico NW, The Queensway West, South of Bloor,..."
179,M9Z,Not assigned,Not assigned

In [16]:
# Choosing only data where field Borough doesn't have not assigned value
raw_data_selected = data[data['Borough'] != 'Not assigned']
raw_data_selected

,Postal Code,Borough,Neighbourhood
2,M3A,North York,Parkwoods
3,M4A,North York,Victoria Village
4,M5A,Downtown Toronto,"Regent Park, Harbourfront"
5,M6A,North York,"Lawrence Manor, Lawrence Heights"
6,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government"
...,...,...,...
160,M8X,Etobicoke,"The Kingsway, Montgomery Road, Old Mill North"
165,M4Y,Downtown Toronto,Church and Wellesley
168,M7Y,East Toronto,"Business reply mail Processing Centre, South C..."
169,M8Y,Etobicoke,"Old Mill South, King's Mill Park, Sunnylea, Hu..."
178,M8Z,Etobicoke,"Mimico NW, The Queensway West, South of Bloor,..."

In [15]:
# Group the Data
group = raw_data_selected.groupby(['Borough', 'Postal Code'], as_index=False).agg(','.join)
group

,Borough,Postal Code,Neighbourhood
0,Central Toronto,M4N,Lawrence Park
1,Central Toronto,M4P,Davisville North
2,Central Toronto,M4R,"North Toronto West, Lawrence Park"
3,Central Toronto,M4S,Davisville
4,Central Toronto,M4T,"Moore Park, Summerhill East"
...,...,...,...
98,York,M6C,Humewood-Cedarvale
99,York,M6E,Caledonia-Fairbanks
100,York,M6M,"Del Ray, Mount Dennis, Keelsdale and Silverthorn"
101,York,M6N,"Runnymede, The Junction North"
102,York,M9N,Weston

In [18]:
# Replacing values in Neighbourhood field with Borough where Neighbourhood is not assigned
old_value = raw_data_selected['Neighbourhood'] == 'Not assigned'
old_value

2      False
3      False
4      False
5      False
6      False
       ...
160    False
165    False
168    False
169    False
178    False
Name: Neighbourhood, Length: 103, dtype: bool

In [19]:
change = data.iloc[:, [2]] 
change

                                         Neighbourhood
0                                         Not assigned
1                                         Not assigned
2                                            Parkwoods
3                                     Victoria Village
4                            Regent Park, Harbourfront
..                                                 ...
175                                       Not assigned
176                                       Not assigned
177                                       Not assigned
178  Mimico NW, The Queensway West, South of Bloor,...
179                                       Not assigned

[180 rows x 1 columns]

In [20]:
# Shape of Data
raw_data_selected.shape

(103, 3)